org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dorg.gradle.internal.http.connectionTimeout=120000 -Dorg.gradle.internal.http.socketTimeout=120000
android.suppressUnsupportedCompileSdk=36,35
android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.newDsl=false
android.builder.sdkDownload=false
android.ndkVersion=28.2.13676358
systemProp.http.keepAlive=true
systemProp.https.protocols=TLSv1.2,TLSv1.3
android.externalNativeBuild.cmake.version=3.22.1

